/*
 * Rotten Tomatoes
 * Test our API services using I/O Docs.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DetailedInfoApi
 */
@Disabled
public class DetailedInfoApiTest {

    private static DetailedInfoApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new DetailedInfoApi(apiClient);
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findSimilarMoviesTest() throws ApiException {
        String id = null;
        String limit = null;
        api.findSimilarMovies(id)
                .limit(limit)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getClipByIdTest() throws ApiException {
        String id = null;
        api.getClipById(id)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMovieAliasInfoTest() throws ApiException {
        String id = null;
        String type = null;
        api.getMovieAliasInfo()
                .id(id)
                .type(type)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMovieByIdJsonTest() throws ApiException {
        String id = null;
        api.getMovieByIdJson(id)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMovieCastTest() throws ApiException {
        String id = null;
        api.getMovieCast(id)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMovieReviewsTest() throws ApiException {
        String id = null;
        String reviewType = null;
        String pageLimit = null;
        String page = null;
        String country = null;
        api.getMovieReviews(id)
                .reviewType(reviewType)
                .pageLimit(pageLimit)
                .page(page)
                .country(country)
                .execute();
        // TODO: test validations
    }

}
