/*
 * Rotten Tomatoes
 * Test our API services using I/O Docs.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DvdListsApi
 */
@Disabled
public class DvdListsApiTest {

    private static DvdListsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new DvdListsApi(apiClient);
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCurrentReleasesTest() throws ApiException {
        String pageLimit = null;
        String page = null;
        String country = null;
        api.getCurrentReleases()
                .pageLimit(pageLimit)
                .page(page)
                .country(country)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNewReleasesJsonTest() throws ApiException {
        String pageLimit = null;
        String page = null;
        String country = null;
        api.getNewReleasesJson()
                .pageLimit(pageLimit)
                .page(page)
                .country(country)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTopRentalsJsonTest() throws ApiException {
        String limit = null;
        String country = null;
        api.getTopRentalsJson()
                .limit(limit)
                .country(country)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUpcomingDvdsTest() throws ApiException {
        String pageLimit = null;
        String page = null;
        String country = null;
        api.getUpcomingDvds()
                .pageLimit(pageLimit)
                .page(page)
                .country(country)
                .execute();
        // TODO: test validations
    }

}
