/*
 * Rotten Tomatoes
 * Test our API services using I/O Docs.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class DvdListsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DvdListsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public DvdListsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getKey() == null) {
            throw new IllegalArgumentException("\"apikey\" is required but no API key was provided. Please set \"apikey\" with ApiClient#setKey(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getCurrentReleasesCall(String pageLimit, String page, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/lists/dvds/current_releases.json";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageLimit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_limit", pageLimit));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "key" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCurrentReleasesValidateBeforeCall(String pageLimit, String page, String country, final ApiCallback _callback) throws ApiException {
        return getCurrentReleasesCall(pageLimit, page, country, _callback);

    }


    private ApiResponse<Void> getCurrentReleasesWithHttpInfo(String pageLimit, String page, String country) throws ApiException {
        okhttp3.Call localVarCall = getCurrentReleasesValidateBeforeCall(pageLimit, page, country, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call getCurrentReleasesAsync(String pageLimit, String page, String country, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCurrentReleasesValidateBeforeCall(pageLimit, page, country, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class GetCurrentReleasesRequestBuilder {
        private String pageLimit;
        private String page;
        private String country;

        private GetCurrentReleasesRequestBuilder() {
        }

        /**
         * Set pageLimit
         * @param pageLimit The amount of new release dvds to show per page (optional, default to 16)
         * @return GetCurrentReleasesRequestBuilder
         */
        public GetCurrentReleasesRequestBuilder pageLimit(String pageLimit) {
            this.pageLimit = pageLimit;
            return this;
        }
        
        /**
         * Set page
         * @param page The selected page of current DVD releases (optional, default to 1)
         * @return GetCurrentReleasesRequestBuilder
         */
        public GetCurrentReleasesRequestBuilder page(String page) {
            this.page = page;
            return this;
        }
        
        /**
         * Set country
         * @param country Provides localized data for the selected country (ISO 3166-1 alpha-2) if available. Otherwise, returns US data. (optional, default to us)
         * @return GetCurrentReleasesRequestBuilder
         */
        public GetCurrentReleasesRequestBuilder country(String country) {
            this.country = country;
            return this;
        }
        
        /**
         * Build call for getCurrentReleases
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getCurrentReleasesCall(pageLimit, page, country, _callback);
        }


        /**
         * Execute getCurrentReleases request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            getCurrentReleasesWithHttpInfo(pageLimit, page, country);
        }

        /**
         * Execute getCurrentReleases request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return getCurrentReleasesWithHttpInfo(pageLimit, page, country);
        }

        /**
         * Execute getCurrentReleases request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return getCurrentReleasesAsync(pageLimit, page, country, _callback);
        }
    }

    /**
     * 
     * 
     * @return GetCurrentReleasesRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public GetCurrentReleasesRequestBuilder getCurrentReleases() throws IllegalArgumentException {
        return new GetCurrentReleasesRequestBuilder();
    }
    private okhttp3.Call getNewReleasesJsonCall(String pageLimit, String page, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/lists/dvds/new_releases.json";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageLimit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_limit", pageLimit));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "key" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getNewReleasesJsonValidateBeforeCall(String pageLimit, String page, String country, final ApiCallback _callback) throws ApiException {
        return getNewReleasesJsonCall(pageLimit, page, country, _callback);

    }


    private ApiResponse<Void> getNewReleasesJsonWithHttpInfo(String pageLimit, String page, String country) throws ApiException {
        okhttp3.Call localVarCall = getNewReleasesJsonValidateBeforeCall(pageLimit, page, country, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call getNewReleasesJsonAsync(String pageLimit, String page, String country, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = getNewReleasesJsonValidateBeforeCall(pageLimit, page, country, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class GetNewReleasesJsonRequestBuilder {
        private String pageLimit;
        private String page;
        private String country;

        private GetNewReleasesJsonRequestBuilder() {
        }

        /**
         * Set pageLimit
         * @param pageLimit The amount of new release dvds to show per page (optional, default to 16)
         * @return GetNewReleasesJsonRequestBuilder
         */
        public GetNewReleasesJsonRequestBuilder pageLimit(String pageLimit) {
            this.pageLimit = pageLimit;
            return this;
        }
        
        /**
         * Set page
         * @param page The selected page of new release DVDs (optional, default to 1)
         * @return GetNewReleasesJsonRequestBuilder
         */
        public GetNewReleasesJsonRequestBuilder page(String page) {
            this.page = page;
            return this;
        }
        
        /**
         * Set country
         * @param country Provides localized data for the selected country (ISO 3166-1 alpha-2) if available. Otherwise, returns US data. (optional, default to us)
         * @return GetNewReleasesJsonRequestBuilder
         */
        public GetNewReleasesJsonRequestBuilder country(String country) {
            this.country = country;
            return this;
        }
        
        /**
         * Build call for getNewReleasesJson
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getNewReleasesJsonCall(pageLimit, page, country, _callback);
        }


        /**
         * Execute getNewReleasesJson request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            getNewReleasesJsonWithHttpInfo(pageLimit, page, country);
        }

        /**
         * Execute getNewReleasesJson request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return getNewReleasesJsonWithHttpInfo(pageLimit, page, country);
        }

        /**
         * Execute getNewReleasesJson request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return getNewReleasesJsonAsync(pageLimit, page, country, _callback);
        }
    }

    /**
     * 
     * 
     * @return GetNewReleasesJsonRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public GetNewReleasesJsonRequestBuilder getNewReleasesJson() throws IllegalArgumentException {
        return new GetNewReleasesJsonRequestBuilder();
    }
    private okhttp3.Call getTopRentalsJsonCall(String limit, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/lists/dvds/top_rentals.json";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "key" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTopRentalsJsonValidateBeforeCall(String limit, String country, final ApiCallback _callback) throws ApiException {
        return getTopRentalsJsonCall(limit, country, _callback);

    }


    private ApiResponse<Void> getTopRentalsJsonWithHttpInfo(String limit, String country) throws ApiException {
        okhttp3.Call localVarCall = getTopRentalsJsonValidateBeforeCall(limit, country, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call getTopRentalsJsonAsync(String limit, String country, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTopRentalsJsonValidateBeforeCall(limit, country, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class GetTopRentalsJsonRequestBuilder {
        private String limit;
        private String country;

        private GetTopRentalsJsonRequestBuilder() {
        }

        /**
         * Set limit
         * @param limit Limits the number of top rentals returned (optional, default to 10)
         * @return GetTopRentalsJsonRequestBuilder
         */
        public GetTopRentalsJsonRequestBuilder limit(String limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Set country
         * @param country Provides localized data for the selected country (ISO 3166-1 alpha-2) if available. Otherwise, returns US data. (optional, default to us)
         * @return GetTopRentalsJsonRequestBuilder
         */
        public GetTopRentalsJsonRequestBuilder country(String country) {
            this.country = country;
            return this;
        }
        
        /**
         * Build call for getTopRentalsJson
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getTopRentalsJsonCall(limit, country, _callback);
        }


        /**
         * Execute getTopRentalsJson request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            getTopRentalsJsonWithHttpInfo(limit, country);
        }

        /**
         * Execute getTopRentalsJson request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return getTopRentalsJsonWithHttpInfo(limit, country);
        }

        /**
         * Execute getTopRentalsJson request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return getTopRentalsJsonAsync(limit, country, _callback);
        }
    }

    /**
     * 
     * 
     * @return GetTopRentalsJsonRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public GetTopRentalsJsonRequestBuilder getTopRentalsJson() throws IllegalArgumentException {
        return new GetTopRentalsJsonRequestBuilder();
    }
    private okhttp3.Call getUpcomingDvdsCall(String pageLimit, String page, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/lists/dvds/upcoming.json";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageLimit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page_limit", pageLimit));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "key" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getUpcomingDvdsValidateBeforeCall(String pageLimit, String page, String country, final ApiCallback _callback) throws ApiException {
        return getUpcomingDvdsCall(pageLimit, page, country, _callback);

    }


    private ApiResponse<Void> getUpcomingDvdsWithHttpInfo(String pageLimit, String page, String country) throws ApiException {
        okhttp3.Call localVarCall = getUpcomingDvdsValidateBeforeCall(pageLimit, page, country, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call getUpcomingDvdsAsync(String pageLimit, String page, String country, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = getUpcomingDvdsValidateBeforeCall(pageLimit, page, country, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class GetUpcomingDvdsRequestBuilder {
        private String pageLimit;
        private String page;
        private String country;

        private GetUpcomingDvdsRequestBuilder() {
        }

        /**
         * Set pageLimit
         * @param pageLimit The amount of upcoming dvds to show per page (optional, default to 16)
         * @return GetUpcomingDvdsRequestBuilder
         */
        public GetUpcomingDvdsRequestBuilder pageLimit(String pageLimit) {
            this.pageLimit = pageLimit;
            return this;
        }
        
        /**
         * Set page
         * @param page The selected page of upcoming DVDs (optional, default to 1)
         * @return GetUpcomingDvdsRequestBuilder
         */
        public GetUpcomingDvdsRequestBuilder page(String page) {
            this.page = page;
            return this;
        }
        
        /**
         * Set country
         * @param country Provides localized data for the selected country (ISO 3166-1 alpha-2) if available. Otherwise, returns US data. (optional, default to us)
         * @return GetUpcomingDvdsRequestBuilder
         */
        public GetUpcomingDvdsRequestBuilder country(String country) {
            this.country = country;
            return this;
        }
        
        /**
         * Build call for getUpcomingDvds
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getUpcomingDvdsCall(pageLimit, page, country, _callback);
        }


        /**
         * Execute getUpcomingDvds request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            getUpcomingDvdsWithHttpInfo(pageLimit, page, country);
        }

        /**
         * Execute getUpcomingDvds request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return getUpcomingDvdsWithHttpInfo(pageLimit, page, country);
        }

        /**
         * Execute getUpcomingDvds request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
            <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
            <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return getUpcomingDvdsAsync(pageLimit, page, country, _callback);
        }
    }

    /**
     * 
     * 
     * @return GetUpcomingDvdsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
     </table>
     */
    public GetUpcomingDvdsRequestBuilder getUpcomingDvds() throws IllegalArgumentException {
        return new GetUpcomingDvdsRequestBuilder();
    }
}
